"""empty message

Revision ID: a2e4ac7f287e
Revises: aad5b013efed
Create Date: 2019-01-29 16:52:39.590442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e4ac7f287e'
down_revision = 'aad5b013efed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name_index', table_name='domains')
    op.drop_table('domains')
    op.drop_index('ip_nameserver_pk', table_name='supermasters')
    op.drop_table('supermasters')
    op.drop_index('domainmetaidindex', table_name='domainmetadata')
    op.drop_table('domainmetadata')
    op.drop_index('domainidindex', table_name='cryptokeys')
    op.drop_table('cryptokeys')
    op.drop_index('comments_domain_id_index', table_name='comments')
    op.drop_index('comments_nametype_index', table_name='comments')
    op.drop_index('comments_order_idx', table_name='comments')
    op.drop_table('comments')
    op.drop_index('namealgoindex', table_name='tsigkeys')
    op.drop_table('tsigkeys')
    op.drop_index('domain_id', table_name='records')
    op.drop_index('nametype_index', table_name='records')
    op.drop_index('orderindex', table_name='records')
    op.drop_index('rec_name_index', table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain_id', sa.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), server_default=sa.text('NULL'), nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), server_default=sa.text('NULL'), nullable=True),
    sa.Column('content', sa.VARCHAR(length=65535), server_default=sa.text('NULL'), nullable=True),
    sa.Column('ttl', sa.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('prio', sa.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('disabled', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('ordername', sa.VARCHAR(length=255), nullable=True),
    sa.Column('auth', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('rec_name_index', 'records', ['name'], unique=False)
    op.create_index('orderindex', 'records', ['ordername'], unique=False)
    op.create_index('nametype_index', 'records', ['name', 'type'], unique=False)
    op.create_index('domain_id', 'records', ['domain_id'], unique=False)
    op.create_table('tsigkeys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('algorithm', sa.VARCHAR(length=50), nullable=True),
    sa.Column('secret', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('namealgoindex', 'tsigkeys', ['name', 'algorithm'], unique=1)
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('modified_at', sa.INTEGER(), nullable=False),
    sa.Column('account', sa.VARCHAR(length=40), server_default=sa.text('NULL'), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=65535), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comments_order_idx', 'comments', ['domain_id', 'modified_at'], unique=False)
    op.create_index('comments_nametype_index', 'comments', ['name', 'type'], unique=False)
    op.create_index('comments_domain_id_index', 'comments', ['domain_id'], unique=False)
    op.create_table('cryptokeys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain_id', sa.INTEGER(), nullable=False),
    sa.Column('flags', sa.INTEGER(), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('domainidindex', 'cryptokeys', ['domain_id'], unique=False)
    op.create_table('domainmetadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('domain_id', sa.INTEGER(), nullable=False),
    sa.Column('kind', sa.VARCHAR(length=32), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('domainmetaidindex', 'domainmetadata', ['domain_id'], unique=False)
    op.create_table('supermasters',
    sa.Column('ip', sa.VARCHAR(length=64), nullable=False),
    sa.Column('nameserver', sa.VARCHAR(length=255), nullable=False),
    sa.Column('account', sa.VARCHAR(length=40), nullable=False)
    )
    op.create_index('ip_nameserver_pk', 'supermasters', ['ip', 'nameserver'], unique=1)
    op.create_table('domains',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('master', sa.VARCHAR(length=128), server_default=sa.text('NULL'), nullable=True),
    sa.Column('last_check', sa.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('notified_serial', sa.INTEGER(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('account', sa.VARCHAR(length=40), server_default=sa.text('NULL'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('name_index', 'domains', ['name'], unique=1)
    # ### end Alembic commands ###
