"""empty message

Revision ID: dcde302758d4
Revises: 
Create Date: 2019-02-05 08:13:25.900317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcde302758d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmdb_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machinename', sa.String(), nullable=True),
    sa.Column('ipaddress', sa.String(), nullable=True),
    sa.Column('network', sa.String(), nullable=True),
    sa.Column('mem', sa.Integer(), nullable=True),
    sa.Column('cpus', sa.Integer(), nullable=True),
    sa.Column('disk', sa.Integer(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('datacenter', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dns1', sa.String(length=20), nullable=True),
    sa.Column('dns2', sa.String(length=20), nullable=True),
    sa.Column('domainname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=75), nullable=True),
    sa.Column('networkname', sa.String(length=50), nullable=True),
    sa.Column('vlanid', sa.String(length=25), nullable=True),
    sa.Column('datacenter', sa.String(length=50), nullable=True),
    sa.Column('cluster', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('network_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poolname', sa.String(length=50), nullable=True),
    sa.Column('poolrange', sa.String(length=20), nullable=True),
    sa.Column('subnetmask', sa.String(length=20), nullable=True),
    sa.Column('gateway', sa.String(length=20), nullable=True),
    sa.Column('dns1', sa.String(length=20), nullable=True),
    sa.Column('dns2', sa.String(length=20), nullable=True),
    sa.Column('domainname', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['networks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipaddress', sa.String(length=20), nullable=True),
    sa.Column('machinename', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('rangeid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rangeid'], ['network_pools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags_junction_table',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('network_id', sa.Integer(), nullable=True),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['pool_assignments.id'], ),
    sa.ForeignKeyConstraint(['network_id'], ['networks.id'], ),
    sa.ForeignKeyConstraint(['pool_id'], ['network_pools.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.tag_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_junction_table')
    op.drop_table('pool_assignments')
    op.drop_table('network_pools')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('networks')
    op.drop_table('global_settings')
    op.drop_table('cmdb_data')
    # ### end Alembic commands ###
